export const data = [
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1624",
      "Enq No.": "Verbal",
      "Enq Type": "Tender",
      "Enq Title": "Boiler Tube leak monitoring Ph1",
      "End-User": "MEW",
      Plant: "ZSPS",
      Client: "Direct",
      Vendor: "Valmet",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "15/11/22",
    },
    {
      SI: "E-1623",
      "Enq No.": "Verbal",
      "Enq Type": "Tender",
      "Enq Title": "Online Compressor monitoring",
      "End-User": "MEW",
      Plant: "ZSPS",
      Client: "Direct",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saran",
      "Closing Date": "20/10/22",
    },
    {
      SI: "E-1367",
      "Enq No.": "Verbal",
      "Enq Type": "Budgetary",
      "Enq Title": "Spotlight for air compressor",
      "End-User": "MEW",
      Plant: "DEPS",
      Client: "Direct",
      Vendor: "Windrock",
      "Offer Status": "Lead",
      Resp: "Saravana",
      "Closing Date": "18/10/22",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
    {
      SI: "E-1848",
      "Enq No.": 12323,
      "Enq Type": "Tender",
      "Enq Title": "aasas",
      "End-User": "DGCA",
      Plant: "DEPS",
      Client: "Airtec",
      Vendor: "Windrock",
      "Offer Status": "Awaiting Enq.",
      Resp: "Saravana",
      "Closing Date": "2024-01-01",
    },
  ];
  